### ISSUE TITLE
Wrong IP address used by GeoIPResolver

### ISSUE THREAD

**Issue by Idix** [Graylog2/graylog-plugin-map-widget#8]
Hi,

I'm using the new GeoIP resolver but it can't make it to work. Instead of trying to resolve the IP address contained in the field, it always try to resolve the private IP of the server.

Here is the relevant log entry, the private address of the server is 10.2.93.16. The field is called "clientip", I also tried with "testip" for this test sake.

> 2016-04-26 15:38:05,129 DEBUG: org.graylog.plugins.map.geoip.GeoIpResolverEngine - Could not get location from IP 10.2.93.16
com.maxmind.geoip2.exception.AddressNotFoundException: The address 10.2.93.16 is not in the database.
	at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:161) ~[graylog-plugin-map-widget-1.0.0-beta.3.jar:?]
	at com.maxmind.geoip2.DatabaseReader.city(DatabaseReader.java:217) ~[graylog-plugin-map-widget-1.0.0-beta.3.jar:?]
	at org.graylog.plugins.map.geoip.GeoIpResolverEngine.extractGeoLocationInformation(GeoIpResolverEngine.java:100) [graylog-plugin-map-widget-1.0.0-beta.3.jar:?]
	at org.graylog.plugins.map.geoip.GeoIpResolverEngine.filter(GeoIpResolverEngine.java:74) [graylog-plugin-map-widget-1.0.0-beta.3.jar:?]
	at org.graylog.plugins.map.geoip.processor.GeoIpProcessor.process(GeoIpProcessor.java:79) [graylog-plugin-map-widget-1.0.0-beta.3.jar:?]
	at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:56) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:139) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

Java version is the following (Debian 8 backports):
> openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)

Thanks!

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please take a look at our [documentation](http://docs.graylog.org/en/2.0/pages/geolocation.html) on that regard, and post any questions to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Idix** [comment]
Hi,

I think it is an issue, this is what I expected:
Value of field "clientip" is "93.17.43.50"
Value of field "clientip_geolocation" is something like: "48.3137, 7.326"

This is the actual result:
Value of field "clientip" is "93.17.43.50"
Field "clientip_geolocation" doesn't exists.
graylog.log is filled with stacktrace as seen above.

Cheers.

**Comment by edmundoa** [comment]
Could you please share the order of your message processors in System -> Configurations?

**Comment by Idix** [comment]
Sure, here it is:
1. GeoIP Resolver
2. Pipeline Processor
3. Message Filter Chain

Also "clientip" is extracted via a Grok pattern.

**Comment by joschi** [comment]
@Idix Try rearranging the message processors so that the GeoIP Resolver comes last.

**Comment by Idix** [comment]
@joschi That did the trick. Thank you!

**Comment by joschi** [comment]
@Idix Cool, thanks for the update!
@kroepke @edmundoa We should probably emphasize the importance of the order of message processors in our docs a little bit more.

**Comment by Idix** [comment]
@joschi Or just add a description for each plugin in the web interface.
I can guess what "Pipeline Processor" and "GeoIP Resolver" do but I had no idea that "Message Filter Chain" is the actual input's extractors.

**Comment by edmundoa** [comment]
@joschi I will change the wording a bit, and add some bold text for better emphasis, but this point is covered both in the setup documentation, and also in the FAQs.

@Idix The problem is that it's not only the input's extractors. Anyway, adding a description doesn't help if a user doesn't know there is something to change in there. Ideally the list of processors would be in the "right" order by default.

**Comment by edmundoa** [comment]
I hope this clarify things a bit in the docs: https://github.com/Graylog2/documentation/commit/7afb5230791ec5c012a10077ccffd3829dfa3a0a
